# Generated by Django 4.1.7 on 2025-04-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kanji",
            name="wrong_option1",
        ),
        migrations.RemoveField(
            model_name="kanji",
            name="wrong_option2",
        ),
    ]
